project_id = "bzzstdpfmyqttnzhgaoa"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[functions.spotify-auth]
verify_jwt = true

[functions.spotify-sync-liked]
verify_jwt = true

[functions.spotify-unlike-tracks]
verify_jwt = true

[functions.discogs-auth]
verify_jwt = true

[functions.discogs-search]
verify_jwt = true

[functions.genre-mapping]
verify_jwt = true

[functions.ai-track-genre-suggest]
verify_jwt = true

[functions.discogs-sync-from-collection]
verify_jwt = true

[functions.discogs-add-to-collection]
verify_jwt = true

[functions.vinyl-image-identify]
verify_jwt = true
